package share.manager.utils;

public enum RESTFunction {
	GET_COMPANY_STOCK,
	GET_COMPANY_RANGE_STOCK,	
	GET_COMPANY_STOCK_PORTFOLIO,
	GET_COMPANY_RANGE_STOCK_PORTFOLIO,
	GET_COMPANY_NAMES,
	VALIDITY_CHECK
}
